name: CI Pipeline

on:
  push:
    branches: [ dev , main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: build 
        run: go build -v ./cmd/main.go